server:
  port: 8002         #当前服务的端口号
  

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:9001/eureka/
  instance: 
    instance-id: CBDSP-landlord-8020 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
spring:
   application:
    name: CBDSP-landlord   #当前服务的名字，后面会用到
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://uf647752du6dt3ee89o.mysql.rds.aliyuncs.com:3306/db_cdbp_user             # 数据库名称
    username: root
    password: hlq19961024@
    dbcp2:
      min-idle: 5                                      # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化连接数
      max-total: 5                                     # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间


info: #监控信息 
  app.name: CBDSP
  company.name: www.cbdsp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$